### ISSUE TITLE
Differences between `tsm` and `esbuild-runner`?

### ISSUE THREAD

**Issue by dashmug** [lukeed/tsm#20]
I just read about differences between `tsm` and `ts-node`. @lukeed's comment there was very helpful. 

Now, I'm curious to know the differences between `tsm` and [`esbuild-runner`](https://github.com/folke/esbuild-runner).

**Comment by lukeed** [comment]
Just by looking at the package quickly for the first time:

- tsm supports native ESM and ESM loader usage, esr doesn't
- esr configuration is focused on bundling versus transforming, presumably for plugin support? tsm configuration is on a per-file/extension basis, so it's equally/more configurable but is always in transform mode (better, imo, since it's how require/loader hooks are expected to be used
- tsm does a bunch of cjs->esm (and vice versa) fixes that I don't think esr does
- tsm adds extra resolution logic for handling all mts, cts, etc variants


There may be others. Or this may be somewhat inaccurate. This is after looking for 60s. Not super interested in pinning packages against each other. 

Hope this helps though~
